name       : kcrash
version    : 5.93.0
release    : 60
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.93/kcrash-5.93.0.tar.xz : 2ff8d6c6924b2b752ef4a929390606bb55ce2aa55c582927269bd65556992dd6
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
