name       : kcrash
version    : 5.59.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kcrash-5.59.0.tar.xz : b1f525dc97ecf41568b175e8d2063b20be630c6a560f060187652307dea82eaa
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
