name       : kcrash
version    : 5.62.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/kcrash-5.62.0.tar.xz : 9fac9396212148aade4b59665ec1725fa76e229f24c46b601f066e0026eddd2c
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
