name       : kcrash
version    : 5.89.0
release    : 56
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.89/kcrash-5.89.0.tar.xz : 6a19f9826333e33f17fc9d05865e8cf432eb9e14d94c1eb4cbe66f8c1321ec1e
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
