name       : kcrash
version    : 5.75.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/kcrash-5.75.0.tar.xz : 1c8950bf699e4df86c2ebe29a364be53017b45d127c1d052c7ac4ef13b96db3a
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
