name       : kcrash
version    : 5.68.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/kcrash-5.68.0.tar.xz : 60daf2cee87c652619b098b688edce6f993c7960783159cd8be9d9145df29f7f
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
