name       : kcrash
version    : 5.109.0
release    : 69
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/kcrash-5.109.0.tar.xz : 2e96d147803f4fb4f9a3affc9ebf69149d221ab49e78f8561ef80cdcf5b276fb
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
