name       : kcrash
version    : 5.56.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/kcrash-5.56.0.tar.xz : 581e8215212a584886e8d4b6d5c1aac277590bcb343697d8b3653e1c22f6b1e0
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
