name       : kcrash
version    : 5.45.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/kcrash-5.45.0.tar.xz : 7bb20708404a80fc2bec0d2126666b0c18e779beb41198b158c77d8565a8c3db
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
