name       : kcrash
version    : 5.77.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/kcrash-5.77.0.tar.xz : bda5567aca769590fbdd96d82d64ef6200350e3c88029d26c7a3603ce880a84e
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
