name       : kcrash
version    : 5.76.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/kcrash-5.76.0.tar.xz : c4e32254b22f1f02db556be2ad40000cc52cac2e30a35682af3c75ac69710993
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
