name       : kcrash
version    : 5.83.0
release    : 51
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/kcrash-5.83.0.tar.xz : 29ef0273ebd543be5bb9363efe5271fcaaea599463338d8ece625071decfa4c7
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
