name       : kcrash
version    : 5.49.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/kcrash-5.49.0.tar.xz : 6315a1607aba1945d3d91092b9440f222f1bb25a8bf01cb0bd507540734eb976
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
