name       : kcrash
version    : 5.52.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/kcrash-5.52.0.tar.xz : 2b5cd37d67edaba93a9fd90f12889c57bb83c178c58e1635b6204b8e742f9481
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
