name       : kcrash
version    : 5.67.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kcrash-5.67.0.tar.xz : b372e2df0c415b941d7748abf3d0584e3f101d10c0dc4d90fa9087e3355b81ec
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
