name       : kcrash
version    : 5.36.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.36/kcrash-5.36.0.tar.xz : 2d8edd9813b8543cef68cd6cf09c85195999d06f9b06ed0803707a1c925eda38
license    : LGPL-2.1
component  : desktop.library
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
