name       : kcrash
version    : 5.40.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/kcrash-5.40.0.tar.xz : 96d2b2d16317519f95fa9277beca9d4a10f65dac608bfa0783a5823efe0f0406
license    : LGPL-2.1
component  : desktop.library
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
