name       : kcrash
version    : 5.99.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.99/kcrash-5.99.0.tar.xz : e896c42626252e5e0ddb63c469337a7208bc89700c158783cf82df081b67c3f2
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
