name       : kcrash
version    : 5.90.0
release    : 57
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.90/kcrash-5.90.0.tar.xz : 8e002a52c48a5aaec72e85bcc30741b8b2493173030b3bca9e1de5bd3e966418
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
