name       : kcrash
version    : 5.53.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/kcrash-5.53.0.tar.xz : 8b56adfb36b349619b8b2cd5af5f8633c18a48664a76f1b82fed243ac3b1ceda
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
