name       : kcrash
version    : 5.66.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/kcrash-5.66.0.tar.xz : 5a518059de3f3e85ee7b38a0edf348d097993518ce9b17504470f0d8aad3f2e4
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
