name       : kcrash
version    : 5.79.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/kcrash-5.79.0.tar.xz : ecaa74faaf31098acf8974eb5785101b9477fc78a7308a306a6c4d162468e470
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
