name       : kcrash
version    : 5.50.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/kcrash-5.50.0.tar.xz : 846e5febaf0871185b1da6cc33f3620317e7692595a73e793977b570a1f5c202
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
