name       : kcrash
version    : 5.39.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.39/kcrash-5.39.0.tar.xz : 9a0727734745b3050f864f2de1dbdb91e9ac99a49ede9874613427080a1563bb
license    : LGPL-2.1
component  : desktop.library
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
