name       : kcrash
version    : 5.38.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.38/kcrash-5.38.0.tar.xz : 215c90bf6501cb90db01f2a04155bcd8a8e66fcfb4a94649e72204c5a1df10a9
license    : LGPL-2.1
component  : desktop.library
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
