name       : kcrash
version    : 5.48.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/kcrash-5.48.0.tar.xz : 687e352fe400c913217c07407c0257ba70cf9c9d33104849759cfc784f6f1c63
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
