name       : kcrash
version    : 5.35.0
release    : 4
source     :
    - https://download.kde.org/stable/frameworks/5.35/kcrash-5.35.0.tar.xz : 3086f410712132e15d593330c43b64502a059ebb833eea75245b8fab2432140c
license    : LGPL-2.1
component  : desktop.library
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
