name       : kcrash
version    : 5.46.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/kcrash-5.46.0.tar.xz : 309a05d36d4a97638ec0a19a392115fa43255fe9076d15924c9295494f4c3335
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
